Started writing readme for proper info about the project
neel123456/Fragments-Download pull request #1
Opened 2017-06-27 17:34 UTC by him1411

2017-06-27 17:37 UTC, him1411 commented
updated a typo

2017-06-27 17:37 UTC, him1411 commented
updated a typo

2017-06-27 17:38 UTC, aero31aero commented on README.md
> +### BITS Pilani Hyderabad Campus
Unnecessary use of headings. Plus, no need to specify college name at the top.

2017-06-27 17:39 UTC, aero31aero commented on README.md
> -usage: python3 frag.py URL
Add usage in its own section: Dependency installation etc? Also, use single tildes for writing code snippets like: `python3 ...`

2017-06-27 17:39 UTC, aero31aero commented on README.md
> +## Powered by CRUx - The computing and programming club
Powered by sounds too extreme. Again, unnecessary use of heading.

2017-06-27 17:43 UTC, aero31aero commented on README.md
> +![](https://scontent.fbom1-1.fna.fbcdn.net/v/t1.0-1/p200x200/17904452_1491990900819437_3846562565023385004_n.png?oh=4a26af21c3764e36319197a532de47c7&oe=59DFB8EC)
Can this be changed to a better hosted logo? If you have free time, create a PR to add this into the `cruxbphc.github.io` repo and link from there.

2017-06-27 17:44 UTC, aero31aero requested changes
Needs Contributing guide as well as a License. Good draft, keep it up. :)

2017-06-27 17:45 UTC, him1411 commented on README.md
> +## Powered by CRUx - The computing and programming club
will do

2017-06-27 17:46 UTC, him1411 commented on README.md
> +### BITS Pilani Hyderabad Campus
I think college name is kind of essential because the club is because of the college. Just an opinion

2017-06-27 17:48 UTC, him1411 commented on README.md
> -usage: python3 frag.py URL
Writing all that now. Will finish it by tonight

2017-06-27 17:48 UTC, aero31aero commented on README.md
> +### BITS Pilani Hyderabad Campus
But someone happening to come to the README file probably doesn't care about who made this and where but rather, what it does. If they like it, then they'd look at other things. Again, its your project so you could take any route, but that's how I've seen it done.

2017-06-27 17:49 UTC, him1411 commented
will do that by tonight . Thanks

2017-06-27 17:51 UTC, him1411 commented on README.md
> +### BITS Pilani Hyderabad Campus
should I write these things at the bottom then ? will be more suitable I suppose ?

2017-06-27 18:01 UTC, aero31aero commented
Also, closing an issue/PR means its done. You only close them when:
1. The commits have been merged OR issue has been resolved.
2. The commits have been rejected OR issue has been marked as `wont-fix`.

2017-06-27 18:18 UTC, him1411 commented
Didn't know that.Thanks

2017-06-28 12:49 UTC, him1411 commented
Made the changes proposed.

2017-06-28 12:50 UTC, merged